CREATE DATABASE BIBLIOTECA;
USE BIBLIOTECA;

CREATE TABLE LIVROS
(
	Id_LIVRO INTEGER NOT NULL PRIMARY KEY AUTO_INCREMENT,
	NOME_LIVRO VARCHAR(100) NOT NULL,
	AUTOR_LIVRO VARCHAR(50) NOT NULL,
	ANO_LIVRO VARCHAR(30) NOT NULL,
	GENERO_LIVRO VARCHAR(50) NOT NULL,
	EDITORA_LIVRO VARCHAR(50) NOT NULL,
	PAGINAS_LIVRO VARCHAR(50) NOT NULL,
	STATUS_LIVRO CHAR(1) NOT NULL,
	ISBN_LIVRO VARCHAR(50) NOT NULL UNIQUE
);

CREATE TABLE FUNCIONARIOS
(
	Id_FUNCIONARIO INTEGER NOT NULL PRIMARY KEY AUTO_INCREMENT,
	NOME_FUNCIONARIO VARCHAR(100) NOT NULL,
	ENDERECO_FUNCIONARIO VARCHAR(50) NOT NULL,
	CIDADE_FUNCIONARIO VARCHAR(50) NOT NULL,
	ESTADO_FUNCIONARIO VARCHAR(30) NOT NULL,
	TELEFONE_FUNCIONARIO VARCHAR(20) NOT NULL,
	CARGO_FUNCIONARIO VARCHAR(30) NOT NULL,
	CPF VARCHAR(30) NOT NULL UNIQUE
);

CREATE TABLE CLIENTES
(
	Id_CLIENTE INTEGER NOT NULL PRIMARY KEY AUTO_INCREMENT,
	NOME_CLIENTE VARCHAR(100) NOT NULL,
	ENDERECO_CLIENTE VARCHAR(50) NOT NULL,
	CIDADE_CLIENTE VARCHAR(50) NOT NULL,
	ESTADO_CLIENTE  VARCHAR(30) NOT NULL,
	TELEFONE_CLIENTE VARCHAR(20) NOT NULL,
	STATUS_CLIENTE CHAR(1) NOT NULL,
	CPF VARCHAR(30) NOT NULL UNIQUE
);